package DbmsAPP;


/**
* DbmsAPP/DbmsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dbms.idl
* Thursday, December 15, 2016 11:40:21 PM EET
*/

abstract public class DbmsHelper
{
  private static String  _id = "IDL:DbmsAPP/Dbms:1.0";

  public static void insert (org.omg.CORBA.Any a, DbmsAPP.Dbms that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DbmsAPP.Dbms extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DbmsAPP.DbmsHelper.id (), "Dbms");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DbmsAPP.Dbms read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DbmsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DbmsAPP.Dbms value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DbmsAPP.Dbms narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DbmsAPP.Dbms)
      return (DbmsAPP.Dbms)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DbmsAPP._DbmsStub stub = new DbmsAPP._DbmsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DbmsAPP.Dbms unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DbmsAPP.Dbms)
      return (DbmsAPP.Dbms)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DbmsAPP._DbmsStub stub = new DbmsAPP._DbmsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
